/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    DATE_OF_BIRTH DATE,
    ESCAPE_ATTEMPTS INT,
    NEUTERED BOOLEAN,
    WEIGHT_KG DECIMAl
    SPECIES TEXT
);
ALTER TABLE ANIMALS ADD COLUMN species TEXT;

-- Multiple Tables -- 
CREATE TABLE owners (
    ID SERIAL PRIMARY KEY,
    FULL_NAME TEXT,
    AGE INT
);

CREATE TABLE species (
    ID SERIAL PRIMARY KEY,
    NAME TEXT
);

CREATE SEQUENCE animals_id_seq;
ALTER TABLE ANIMALS ALTER COLUMN ID SET DEFAULT NEXTVAL('animals_id_seq');
ALTER TABLE ANIMALS DROP COLUMN species;
ALTER TABLE ANIMALS ADD COLUMN SPECIES_ID INT; 
ALTER TABLE ANIMALS ADD FOREIGN KEY (species_id) REFERENCES species (ID);
ALTER TABLE ANIMALS ADD COLUMN OWNER_ID INT;  
ALTER TABLE ANIMALS ADD FOREIGN KEY (owner_id) REFERENCES owners (ID);